apiVersion: apps/v1
kind: Deployment
metadata:
  name: als-server
  namespace: wsva
  annotations:
    build: "BUILD_TIME"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: als-server
  template:
    metadata:
      labels:
        app: als-server
      annotations:
        build: "BUILD_TIME"
    spec:
      containers:
        - name: als-server
          image: alpine:3.22.0
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              set -e
              apk add --no-cache git
              git clone https://github.com/wsva/als_server_build
              ./als_server_build/als_server
          ports:
            - containerPort: 443
          volumeMounts:
            - name: ssl
              mountPath: /ssl
            - name: docs
              mountPath: /docs
      volumes:
        - name: ssl
          hostPath:
            path: /als/ssl
            type: Directory
        - name: docs
          hostPath:
            path: /docs
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: als-server
  namespace: wsva
spec:
  type: NodePort
  selector:
    app: als-server
  ports:
    - port: 443
      targetPort: 443
      nodePort: 1235